### ISSUE TITLE
how is this even possible, like where you get the numbers

### ISSUE THREAD

**Issue by NotASkidder** [FuckingToasters/discord-phone-verifier#1]

**Comment by FuckingToasters** [comment]
Hi, this is possible by using a API, which give you the number and a order id, using this orderid you can check if a verification code appeard. if so we pass it over to discord and verify the account. if not we wait until the code is there. At the moment there is a bug which give some erros when choosing more than 1 Thread. I'm currently working on a fix.

**Comment by FuckingToasters** [comment]
Yo, i updated the code a lot since you created this issue, please try it again with the new version of the code :)

**Comment by FuckingToasters** [comment]
Closing due to some inactivity.
