### ISSUE TITLE
Error while requesting code via vaksms

### ISSUE THREAD

**Issue by NinaSteve** [FuckingToasters/discord-phone-verifier#12]
[*] Solving captcha... please be patient!
        [+] Successfully requested verification code!
Exception in thread Thread-4 (verify):
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run       
    self._target(*self._args, **self._kwargs)
  File "C:\Users\USER\Desktop\Pictures\Phone-Verify\discord-phone-verifier\new version\main.py", line 221, in verify
    VERIFYCODE = waitsms()
  File "C:\Users\USER\Desktop\Pictures\Phone-Verify\discord-phone-verifier\new version\main.py", line 193, in waitsms
    if str(PHONESERVICE).lower() == "vaksms": waitcount, verifycode = vaksms.getcode()
  File "C:\Users\USER\Desktop\Pictures\Phone-Verify\discord-phone-verifier\new version\plugins\phoneservices\vaksms.py", line 73, in getcode
    with requests.Client() as client: response = client.get(url).json()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_models.py", line 743, in json
    return jsonlib.loads(self.text, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads 
    return _default_decoder.decode(s)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode 
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by FuckingToasters** [comment]
> [*] Solving captcha... please be patient! [+] Successfully requested verification code! Exception in thread Thread-4 (verify): Traceback (most recent call last): File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner self.run() File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run self._target(*self._args, **self._kwargs) File "C:\Users\USER\Desktop\Pictures\Phone-Verify\discord-phone-verifier\new version\main.py", line 221, in verify VERIFYCODE = waitsms() File "C:\Users\USER\Desktop\Pictures\Phone-Verify\discord-phone-verifier\new version\main.py", line 193, in waitsms if str(PHONESERVICE).lower() == "vaksms": waitcount, verifycode = vaksms.getcode() File "C:\Users\USER\Desktop\Pictures\Phone-Verify\discord-phone-verifier\new version\plugins\phoneservices\vaksms.py", line 73, in getcode with requests.Client() as client: response = client.get(url).json() File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx_models.py", line 743, in json return jsonlib.loads(self.text, **kwargs) File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json__init__.py", line 346, in loads return _default_decoder.decode(s) File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

go to plugins/phoneservices/vaksms.py and on line 73 replace the line with this one:
```py
with requests.Client() as client: response = client.get(url)
print(response.text)
```
This will pritnt you the full output from the api and you can send it me, note that a object not subscriptable error will appear and that's expected (because we replaced .json() with .text for debugging?

**Comment by snekROmonoro** [comment]
fix for that:

url = f"https://vak-sms.com/api/getSmsCode/?apiKey={self.APIKEY}&idNum={self.TZID}"

**Comment by FuckingToasters** [comment]
> fix for that:
> 
> url = f"[https://vak-sms.com/api/getSmsCode/?apiKey={self.APIKEY}&idNum={self.TZID}](https://vak-sms.com/api/getSmsCode/?apiKey=%7Bself.APIKEY%7D&idNum=%7Bself.TZID%7D)"

thx, i've updated the variable so it should work now.
