### ISSUE TITLE
Solving Captcha

### ISSUE THREAD

**Issue by GiftStein1** [FuckingToasters/discord-phone-verifier#15]
It stops by Solving the Captcha, I use capmonster with vaksms.

![image](https://user-images.githubusercontent.com/73061040/207001619-2e007b8a-1e53-4746-8fc6-2e269f8a77f1.png)

**Comment by FuckingToasters** [comment]
Could you please try out the new dev branch? i fixed multiple things there, maybe the issue you had is fixed too:
https://github.com/FuckingToasters/discord-phone-verifier/tree/dev

**Comment by GiftStein1** [comment]
Hello still seems to be the same issue

![image](https://user-images.githubusercontent.com/73061040/210097146-47e88cc9-971a-432f-9982-871202697dda.png)

**Comment by FuckingToasters** [comment]
> Hello still seems to be the same issue
> 
> ![image](https://user-images.githubusercontent.com/73061040/210097146-47e88cc9-971a-432f-9982-871202697dda.png)

The issue seem to be in the captchatools libary and not in my script itself. which version of captchatools do you have installed? Personally i have installed version 1.2.1

you can try to uninstall captchatools and then install version 1.2.1

pip uninstall captchatools
pip install captchatools==1.2.1

**Comment by GiftStein1** [comment]
That was the fix! Thank you for the information!
