### ISSUE TITLE
SMS not sent

### ISSUE THREAD

**Issue by Sysys242** [FuckingToasters/discord-phone-verifier#16]
Ayo,
So basicly, i tryed to phone verify, with 5sim & capmonster, and it just not sent
![image](https://user-images.githubusercontent.com/86845555/210179036-a50052d3-6e47-4263-970e-264cb30357ea.png)

Idk if you can fix, or idk, i tried with proxy, without, changing country/operator

if u have any question, i will ansanwer faster in discord : Not Sysy's#6700

Thx :)

**Comment by FuckingToasters** [comment]
Do you use the dev branch version or the one in the main branch? I recommend you to try out the dev branch version if you are not doing so already, otherwise the tokens could be the issue too because in general fivesim, vaksms and smshub work fine.

**Comment by Sysys242** [comment]
Solved by using vak-sms
