### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by KushLobbies** [FuckingToasters/discord-phone-verifier#17]
![image](https://user-images.githubusercontent.com/80484721/210375726-4614cef6-8a05-4fed-968f-0fc918cf39db.png)
do you know the error

**Comment by KushLobbies** [comment]
> ![image](https://user-images.githubusercontent.com/80484721/210375726-4614cef6-8a05-4fed-968f-0fc918cf39db.png) do you know the error

always get failed to get verifacation code

**Comment by FuckingToasters** [comment]
The issue is that you somehow don't get a phonenumber from the selected service so the number variable remains None meaning that it send None as phone number to discord which result in it thinking that no captcha solving is required and thus you get that error.

Which phone service do you use? I don't have this issue with vaksms but if you tell me which service you use, i can take a look into it.

**Comment by KushLobbies** [comment]
> The issue is that you somehow don't get a phonenumber from the selected service so the number variable remains None meaning that it send None as phone number to discord which result in it thinking that no captcha solving is required and thus you get that error.
> 
> Which phone service do you use? I don't have this issue with vaksms but if you tell me which service you use, i can take a look into it.

I’m using 5sim

**Comment by FuckingToasters** [comment]
> > The issue is that you somehow don't get a phonenumber from the selected service so the number variable remains None meaning that it send None as phone number to discord which result in it thinking that no captcha solving is required and thus you get that error.
> > Which phone service do you use? I don't have this issue with vaksms but if you tell me which service you use, i can take a look into it.
> 
> I’m using 5sim

You can try to make following edit to plugins/phoneservices/fivesim.py on line 86 change it to RECEIVED

**Comment by FuckingToasters** [comment]
closed due to inactivity
