### ISSUE TITLE
'{"message": "Invalid phone number", "code": 50022}'

### ISSUE THREAD

**Issue by vst212** [FuckingToasters/discord-phone-verifier#19]
Hi,

Thanks for your greate job and efforts first and I faced some difficulties as phone invalid, no matter 3 provider:
'{"message": "Invalid phone number", "code": 50022}'
I am not sure why such situation happen. Thanks.
![image](https://user-images.githubusercontent.com/47769540/223648477-2acf27c4-1368-4eb9-8b90-3b4dac7356ae.png)

**Comment by FuckingToasters** [comment]
Before that resp2 variable, add print(data1) to see if the phone number is correctly included and then let me know.

I also suggest you to use the Dev branch version if you don't do so already.

**Comment by vst212** [comment]
I see seems normal
![image](https://user-images.githubusercontent.com/47769540/223659497-1ba287f5-c59d-4a24-b663-42db95c45921.png)

**Comment by vst212** [comment]
I mannual tested uk can and when I use bot to triggle seems cannot let discord to send the sms request
![image](https://user-images.githubusercontent.com/47769540/223744764-ec0e8e27-01bd-4760-9727-f891d382dfce.png)

**Comment by vst212** [comment]
sloved the problem, I tunned the timeout, thanks a lots for all the help

**Comment by FuckingToasters** [comment]
> I even use US number of 5 sims also the same case.
> ![image](https://user-images.githubusercontent.com/47769540/223735067-b80b96da-4e7b-4acd-8b5d-d5ced9aa5dea.png)
> 

You can add United States as supported country by yourself. Go to plugins/phone services/vaksms and on I think line 31 you have an country function. Just add United States: us, there and it should work.

**Comment by FuckingToasters** [comment]
> sloved the problem, I tunned the timeout, thanks a lots for all the help

With timeout what do you mean exactly? Do you mean the steps it try to get the number like 1/120, 2/120 etc. or the timeout bomber for httpx (which you prolly can set in config.json)?

**Comment by vst212** [comment]
> > sloved the problem, I tunned the timeout, thanks a lots for all the help
> 
> With timeout what do you mean exactly? Do you mean the steps it try to get the number like 1/120, 2/120 etc. or the timeout bomber for httpx (which you prolly can set in config.json)?

May I ask you a side question. Even if httpx and tls_client library, the local network is also affecting the Cloudflare detection and will traggle error 429, request too much With the proxy used. Is it any way that can Python completely let Cloudflare not detected that as I has another function to join guild. At start it work and keep running, error 429 come again🤣 thanks if any ideas.

**Comment by Taurage** [comment]
getting this error too.

**Comment by FuckingToasters** [comment]
> > > sloved the problem, I tunned the timeout, thanks a lots for all the help
> > 
> > 
> > With timeout what do you mean exactly? Do you mean the steps it try to get the number like 1/120, 2/120 etc. or the timeout bomber for httpx (which you prolly can set in config.json)?
> 
> May I ask you a side question. Even if httpx and tls_client library, the local network is also affecting the Cloudflare detection and will traggle error 429, request too much With the proxy used. Is it any way that can Python completely let Cloudflare not detected that as I has another function to join guild. At start it work and keep running, error 429 come again🤣 thanks if any ideas.

So even when you request an sms resend manually on he website, the statuscode isn't 200 but it still resends the sms without any issue. I'm not sure which ratelimit error you are expirencing, The tool handle ratelimiting well, it get the time you are ratelimited and then continue after the time has passed. After every fith request to get the smscode it request the smscode again from discord which increase the chanche of getting an sms out of it

**Comment by FuckingToasters** [comment]
> > > sloved the problem, I tunned the timeout, thanks a lots for all the help
> > 
> > 
> > With timeout what do you mean exactly? Do you mean the steps it try to get the number like 1/120, 2/120 etc. or the timeout bomber for httpx (which you prolly can set in config.json)?
> 
> May I ask you a side question. Even if httpx and tls_client library, the local network is also affecting the Cloudflare detection and will traggle error 429, request too much With the proxy used. Is it any way that can Python completely let Cloudflare not detected that as I has another function to join guild. At start it work and keep running, error 429 come again🤣 thanks if any ideas.

This is a phone verifier, not a guild joiner. Guild Joiners require a bit more time to develop because you need to do more things (pass rqdata when solving captcha, get a message payload from another endpoint, base64 encode it and send it to the join endpoint as context properties aswell etc.)

**Comment by jjhesk** [comment]
> sloved the problem, I tunned the timeout, thanks a lots for all the help

what is the tunned timeout configuration and how long is the time?

**Comment by jjhesk** [comment]
I still got stuck at this https://github.com/FuckingToasters/discord-phone-verifier/issues/19 @vst212 @FuckingToasters 
1. captcha result from the solution-> response code have been pasted successfully into
 a.  `data1["captcha_key"] = CAPTCHATOKEN`
 b.  `HEADERS["X-Captcha-Key"] = CAPTCHATOKEN`
then call the post request with the modified headers
`resp2 = session.post("https://discord.com/api/v9/users/@me/phone", json=data1, headers=HEADERS)`


If I got to this level 50022 does it meaning I have successfully pass the captcha from the previous challenge? I use yescaptcha solver.



I use many countries numbers and still not getting it pass thru set phone number api, but when I use the browser either Chrome or Firefox I got 100% success rate with using the failed numbers from the previous 50022 result. 

Can tell me a bit more about this issues or anyone who have got the similar experience from this?

<img width="1279" alt="image" src="https://github.com/FuckingToasters/discord-phone-verifier/assets/629338/38e06867-93dd-4632-a0f6-9026486bb3f3">

**Comment by FuckingToasters** [comment]
> I still got stuck at this https://github.com/FuckingToasters/discord-phone-verifier/issues/19 @vst212 @FuckingToasters 
> 1. captcha result from the solution-> response code have been pasted successfully into
>  a.  `data1["captcha_key"] = CAPTCHATOKEN`
>  b.  `HEADERS["X-Captcha-Key"] = CAPTCHATOKEN`
> then call the post request with the modified headers
> `resp2 = session.post("https://discord.com/api/v9/users/@me/phone", json=data1, headers=HEADERS)`
> 
> 
> If I got to this level 50022 does it meaning I have successfully pass the captcha from the previous challenge? I use yescaptcha solver.
> 
> 
> 
> I use many countries numbers and still not getting it pass thru set phone number api, but when I use the browser either Chrome or Firefox I got 100% success rate with using the failed numbers from the previous 50022 result. 
> 
> Can tell me a bit more about this issues or anyone who have got the similar experience from this?
> 
> <img width="1279" alt="image" src="https://github.com/FuckingToasters/discord-phone-verifier/assets/629338/38e06867-93dd-4632-a0f6-9026486bb3f3">
> 
> 

I assume that the issue has do do with the phone number and not with the captchasolution (as mentioned in the response object).

The issue could be that it try to pass the phone number without `+` or 2x `+` to discord.

What phone service you are using?

**Comment by jjhesk** [comment]
I have tried 5sim/hapi/ and some other vendors. Also I have programmed to make sure the country code comes with only one single `+` sign before making the request. I finally I got this solved by using different http clients and not using request from python providers. I am not sure whats underlaying the issue but I have checked with all possible conditions and outcomes.

**Comment by jjhesk** [comment]
we get back to have invalid phone number and not even going to the second step. how to solve that? here we have already using tls client.

**Comment by jjhesk** [comment]
@FuckingToasters if the double check that there is no mistakes from passing `+` in extra or insufficient what other area I should pay attention to?

**Comment by FuckingToasters** [comment]
> @FuckingToasters if the double check that there is no mistakes from passing `+` in extra or insufficient what other area I should pay attention to?

maybe the phone numbers which the sms service provides you with via the apis are detected by discord. you could try to order a number from the phoneservice you use manually and see if it accepts the number via the manual way. if it does then there must be something wrong with the tool (im not sure what as of now tho if thats the case)and if it still shows the invalid number error, even on manual way then the number might actually be flagged and you muight need to choose a different smsprovider. i suggest smshub with england number.
