### ISSUE TITLE
SMS Code Never Received

### ISSUE THREAD

**Issue by Echoooooooooooooooooooooooooooo** [FuckingToasters/discord-phone-verifier#2]
Hi the sms code is never received do you know what could be causing this?

**Comment by FuckingToasters** [comment]
> Hi the sms code is never received do you know what could be causing this?

Can yu provide more context please? How many Threads do you use, maybe some screenshots etc. Sometimes discord just not send the confirmation code. You should try it again using a VPN or another Account.

**Comment by FuckingToasters** [comment]
Yo, i updated the code a lot since you created this issue, please try it again with the new version of the code :)

**Comment by Echoooooooooooooooooooooooooooo** [comment]
> Yo, i updated the code a lot since you created this issue, please try it again with the new version of the code :)

yea it doesnt seem to be working at all now

**Comment by FuckingToasters** [comment]
> > Yo, i updated the code a lot since you created this issue, please try it again with the new version of the code :)
> 
> yea it doesnt seem to be working at all now

You should try to redownload the whole project because i edited more files than just main.py if you have issues with it you need to provide me with more details liek the error you got etc. sadly i can't solve a issue i don't know about.

**Comment by Echoooooooooooooooooooooooooooo** [comment]
> > > Yo, i updated the code a lot since you created this issue, please try it again with the new version of the code :)
> > 
> > 
> > yea it doesnt seem to be working at all now
> 
> You should try to redownload the whole project because i edited more files than just main.py if you have issues with it you need to provide me with more details liek the error you got etc. sadly i can't solve a issue i don't know about.

Ok so the first problem is below, but im able to fix it by copying the original python file. But then there is another problem which is below this one.
Exception in thread Thread-1 (verify):
Traceback (most recent call last):
  File "C:\Users\elija\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\elija\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\elija\OneDrive\Desktop\discord-phone-verifier-main (2)\discord-phone-verifier-main\main.py", line 23, in verify
    host_name, port, username, password = proxy_split[0], proxy_split[1], proxy_split[2], proxy_split[3]
IndexError: list index out of range

The other problem is below after it checks if the token is valid which it is, and after it orders the phone number it says this.
Exception in thread Thread-1 (verify):
Traceback (most recent call last):
  File "C:\Users\elija\OneDrive\Desktop\discord-phone-verifier-main (2)\discord-phone-verifier-main\main.py", line 60, in verify
    if check_token.json()["message"] == "401: Unauthorized":
KeyError: 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\elija\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\elija\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\elija\OneDrive\Desktop\discord-phone-verifier-main (2)\discord-phone-verifier-main\main.py", line 85, in verify
    lock.acquire()
NameError: name 'lock' is not defined

**Comment by FuckingToasters** [comment]
Okay so there is actually only one error which i've messed up. i will solve this in the next code update. This error being that lock is not definied in the scope.

The other proxy error is because you formatted the proxies wrong. In the current public release proxies need to be formatted like this: ip:port:user:pass however, in the next code update i add support for ip:port proxies.

**Comment by FuckingToasters** [comment]
Closing due to some inactivity.
