### ISSUE TITLE
[Suggestion] Reduce number usage

### ISSUE THREAD

**Issue by GiftStein1** [FuckingToasters/discord-phone-verifier#23]
If a new number was requested because the other one didn't have a code within 2 minutes and then a code came after 2 minutes, 1 number was wasted. Maybe you could add a cancel request for the number before ordering a new? It's on VAK-SMS big issue with delivery time for the code

**Comment by FuckingToasters** [comment]
That's what it should do already. whenever 120/120 is reached, waitcount will be set to "TIMEOUT" and then the number should be deleted from the phoneservices. maybe there is an issue with this feature on vaksms, if so you might need to print out the full api response for the delete request in the delete function and then tell me what the response is.

Here in main.py on line 239 (dev branch): `if str(PHONESERVICE).lower() == "vaksms": vaksms.deletenumber()`

the function is defined in plugins/phoneservices/vaksms.py on line 68 (dev branch) so inside this deletenumber function below the response variable definition on line 70, you can make a new line and add `print(response)` or make it on the same line so you would edit line 70 to this: `response = requests.get(url).json(); print(response)`

This won't magically fix the issue (if any) but it will give you more info about the issue by writing the full api response to the console so if there is an issue, you can let me know the api response and then i can work on an fix.
