### ISSUE TITLE
[BUG] Invalid Google Sitekey

### ISSUE THREAD

**Issue by sznggs** [FuckingToasters/discord-phone-verifier#4]
invalid google sitekey

**Comment by FuckingToasters** [comment]
> 

Hi, thank you for the Information. I updated the sitekey in files/config.json on the repo. you should replace it locally to fix this BUG

**Comment by craigslol** [comment]
thank you

**Comment by craigslol** [comment]
> > 
> 
> Hi, thank you for the Information. I updated the sitekey in files/config.json on the repo. you should replace it locally to fix this BUG



> > 
> 
> Hi, thank you for the Information. I updated the sitekey in files/config.json on the repo. you should replace it locally to fix this BUG

it keeps getting stuck on solving captcha, do you have discord so i can show proof

**Comment by FuckingToasters** [comment]
Sure, you can find the always up to date discord guild here: https://discord.verify.gay

**Comment by craigslol** [comment]
> Sure, you can find the always up to date discord guild here: https://discord.verify.gay

keep getting this 

Exception in thread Thread-1 (verify):
Traceback (most recent call last):
  File "C:\Users\klove\OneDrive\Desktop\discord-phone-verifier-main\main.py", line 72, in verify
    if check_token.json()["message"] == "401: Unauthorized":
KeyError: 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\klove\OneDrive\Desktop\discord-phone-verifier-main\main.py", line 111, in verify
    captcha_token = solver.get_token()
  File "C:\Users\klove\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\captchatools\harvesters.py", line 46, in get_token
    return self.harvester.get_token()
  File "C:\Users\klove\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\captchatools\capmonster.py", line 18, in get_token
    return self.get_answer( self.get_id()  )
  File "C:\Users\klove\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\captchatools\capmonster.py", line 68, in get_id
    raise captchaExceptions.WrongSitekeyException()
captchatools.exceptions.WrongSitekeyException: [captchatools] Incorrect google sitekey

**Comment by FuckingToasters** [comment]
> > Sure, you can find the always up to date discord guild here: https://discord.verify.gay
> 
> keep getting this
> 
> Exception in thread Thread-1 (verify): Traceback (most recent call last): File "C:\Users\klove\OneDrive\Desktop\discord-phone-verifier-main\main.py", line 72, in verify if check_token.json()["message"] == "401: Unauthorized": KeyError: 'message'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner self.run() File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run self._target(*self._args, **self._kwargs) File "C:\Users\klove\OneDrive\Desktop\discord-phone-verifier-main\main.py", line 111, in verify captcha_token = solver.get_token() File "C:\Users\klove\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\captchatools\harvesters.py", line 46, in get_token return self.harvester.get_token() File "C:\Users\klove\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\captchatools\capmonster.py", line 18, in get_token return self.get_answer( self.get_id() ) File "C:\Users\klove\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\captchatools\capmonster.py", line 68, in get_id raise captchaExceptions.WrongSitekeyException() captchatools.exceptions.WrongSitekeyException: [captchatools] Incorrect google sitekey

Could you send a screenshot of your config.json file here in this issue? only remove your API-Keys before doing so.

**Comment by craigslol** [comment]
> > > Sure, you can find the always up to date discord guild here: https://discord.verify.gay
> > 
> > 
> > keep getting this
> > Exception in thread Thread-1 (verify): Traceback (most recent call last): File "C:\Users\klove\OneDrive\Desktop\discord-phone-verifier-main\main.py", line 72, in verify if check_token.json()["message"] == "401: Unauthorized": KeyError: 'message'
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner self.run() File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run self._target(*self._args, **self._kwargs) File "C:\Users\klove\OneDrive\Desktop\discord-phone-verifier-main\main.py", line 111, in verify captcha_token = solver.get_token() File "C:\Users\klove\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\captchatools\harvesters.py", line 46, in get_token return self.harvester.get_token() File "C:\Users\klove\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\captchatools\capmonster.py", line 18, in get_token return self.get_answer( self.get_id() ) File "C:\Users\klove\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\captchatools\capmonster.py", line 68, in get_id raise captchaExceptions.WrongSitekeyException() captchatools.exceptions.WrongSitekeyException: [captchatools] Incorrect google sitekey
> 
> Could you send a screenshot of your config.json file here in this issue? only remove your API-Keys before doing so.

![image](https://user-images.githubusercontent.com/106770455/178912802-1ef4c6bc-2dd7-4ea8-8e53-39b421400362.png)

**Comment by FuckingToasters** [comment]
hmm this seem to be correct. maybe it helps you if you completly redownload the repo. meanwhile i try it myself on replit and let you know, if i have the same issue.

**Comment by craigslol** [comment]
okayu

**Comment by FuckingToasters** [comment]
did it worked for you so far? i tried it on repl.it but can't even execute it there duruing some weird repl.it related issues.

**Comment by craigslol** [comment]
> 

nope :/

**Comment by FuckingToasters** [comment]
i now solved the issue on replit and can run the script there. could you share a few tokens with me so i can test it? yk my name on discord already.

**Comment by FuckingToasters** [comment]
I think, that i've solved the issue. i added a correct sitekey and aftwards i tried to run the code again and then everything went smoothly as expected.
