### ISSUE TITLE
[ENCHANCEMENT] Add 5sim support

### ISSUE THREAD

**Issue by Valemy** [FuckingToasters/discord-phone-verifier#6]
yo , discord never send verification  code

**Comment by FuckingToasters** [comment]
> yo , discord never send verification code

Which captcha solving service do you use?

**Comment by Valemy** [comment]
capmonster

**Comment by Valemy** [comment]
everythings work fine just vak sms dont send verif number

**Comment by Valemy** [comment]
any way you make a version with 5sim ? they instant send verification code

**Comment by FuckingToasters** [comment]
> capmonster

i guess that's the issue, i had multiple users telling me the same in discord dms and after they switched to anticaptcha everything worked fine. I can implement 5sim later tho.

**Comment by Valemy** [comment]
yes plz would be awesome

**Comment by cheemzboi** [comment]
@Valemy u have a 5sim api key if yes i can add it

**Comment by CannardVC** [comment]
> @Valemy u have a 5sim api key if yes i can add it 

I does have one yes

**Comment by cheemzboi** [comment]
send to me in discord  SKB#6687

**Comment by CannardVC** [comment]
> send to me in discord  SKB#6687  

Like why you need my key to make the edit cant you just do it with ""

**Comment by cheemzboi** [comment]
oh wow very good seems like you don't know the word "ERROR" & "TESTING"

**Comment by cheemzboi** [comment]
maybe u think i m a itty bitty online kiddo who will scam u for ur api key lol

**Comment by FuckingToasters** [comment]
> > send to me in discord  SKB#6687  
> 
> Like why you need my key to make the edit cant you just do it with ""

I can woke on adding it today, i won't need your API Key for it because everything is documented, all their responses etc so you don't need to test the responses yourself with your own API Key.

**Comment by FuckingToasters** [comment]
5sim just added, redownload the whole project cause multiple files have been updated.
