### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by byekazeNET** [FuckingToasters/discord-phone-verifier#8]
Hey, I am trying out the new version and also read ur tip about using anticaptcha to fix it and I started using it, somehow still doesn‘t work with vaksms, do i need to paste my own useragents in the file and what proxy provider would you recommend?

**Comment by FuckingToasters** [comment]
> Hey, I am trying out the new version and also read ur tip about using anticaptcha to fix it and I started using it, somehow still doesn‘t work with vaksms, do i need to paste my own useragents in the file and what proxy provider would you recommend?

Hi, you don't need to change the useragents.txt file, it include most commonly used ones and on every thread select a random one from the file. I do't think the issue has anything to do with the headers.

Usually Anticaptcha works fine however it still could be a issue with captcha solving. capmonster seem to be flagged by discord. I'm not sure about 2captcha but you could try 2captcha; maybe it helps

For your question on which proxies i'm using, i use my own proxies for it.
