### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by TheCannard38** [FuckingToasters/discord-phone-verifier#9]
i get many errors due to proxies what proxies provider you use for your tool

**Comment by FuckingToasters** [comment]
> i get many errors due to proxies what proxies provider you use for your tool

I'm using my own proxies for my tools and for other tools

**Comment by TheCannard38** [comment]
and you dont know good proxy provider that could make it go smooth ?

**Comment by FuckingToasters** [comment]
> and you dont know good proxy provider that could make it go smooth ?

you could try my proxies, they should work better, i can give you a test ofc.

**Comment by TheCannard38** [comment]
ok can you give me your discord ?

**Comment by FuckingToasters** [comment]
> ok can you give me your discord ?

https://discord.gg/eb78EgFc

Infinimonster#0001
